Repository nullisdefined/nanalmoa-BE, pull requests merged in 2024-09, with the labels that each got.

#1 [DOCS] Swagger API Docs 작성
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.spec.ts
  src/database/seeds/create-initial-data.ts
  src/main.ts
  src/modules/group/dto/create-group.dto.ts
  src/modules/group/dto/update-group.dto.ts
  src/modules/group/group.controller.ts
  src/modules/group/group.module.ts
  src/modules/group/group.service.ts
  src/modules/schedules/schedules.controller.ts
  src/modules/share/dto/create-share.dto.ts
  src/modules/share/dto/update-share.dto.ts
  src/modules/share/entities/share.entity.ts
  src/modules/share/share.controller.spec.ts
  src/modules/share/share.controller.ts
  src/modules/share/share.module.ts
  src/modules/share/share.service.spec.ts
  src/modules/share/share.service.ts
  src/modules/users/users.controller.ts
  swagger.json
Labels: documentation

#28 [DOCS] 특정 날짜 범위의 일정 조회 기능 스웨거 문서 쿼리 업데이트
  src/modules/schedules/dto/data-range-schedule.dto.ts
  src/modules/schedules/schedules.controller.ts
  src/modules/schedules/schedules.service.ts
Labels: documentation

#30 [FEAT] 음성 인식 및 일정 추출 기능 구현
  package-lock.json
  package.json
  src/modules/schedules/dto/voice-schedule.dto.ts
  src/modules/schedules/schedules.controller.ts
  src/modules/schedules/schedules.module.ts
  src/modules/schedules/schedules.service.spec.ts
  src/modules/schedules/schedules.service.ts
  swagger.json
Labels: enhancement

#32 [DOCS] 음성 관련 일정 등록 VoiceScheduleUploadDto swagger update
  src/modules/schedules/dto/voice-schedule.dto.ts
  swagger.json
Labels: documentation

#34 fix: gpt 모델JSON 파싱 에러 해결
  src/modules/schedules/schedules.service.ts
Labels: bug

#42 [FiX] 카테고리 아이디 대신 카테고리 객체 반환
  src/modules/schedules/dto/voice-schedule.dto.ts
  src/modules/schedules/schedules.service.ts
Labels: bug, enhancement

#44 [FEAT] 음성 전사 서비스 분리 및 개선
  src/modules/schedules/schedules.controller.ts
  src/modules/schedules/schedules.module.ts
  src/modules/schedules/schedules.service.ts
  src/modules/schedules/voice-transcription.service.ts
  swagger.json
Labels: documentation, enhancement
