Repository nullisdefined/nanalmoa-BE, pull requests merged in 2024-10, with the labels that each got.

#54 관리자관련 엔티티 작성;
  src/entities/manager-invitation.entity.ts
  src/entities/manager-subordinate.entity.ts
Labels: enhancement

#59 [REMOVE] Auth, Users 테스팅 코드 삭제
  .github/workflows/nodejs-ci.yml
  package-lock.json
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/dto/refresh-token.dto.ts
  src/auth/strategies/jwt.strategy.ts
  src/main.ts
Labels: bug

#65 feat/manager 관련 dto 생성
  src/modules/manager/dto/create-invitation.dto.ts
  src/modules/manager/dto/create-manager.dto.ts
  src/modules/manager/dto/response-invitation.dto.ts
  src/modules/manager/dto/update-invitation.dto.ts
Labels: enhancement

#67 feat/manager invitation 관련 api 구현
  src/app.module.ts
  src/dataSource.ts
  src/entities/manager-invitation.entity.ts
  src/modules/manager/dto/get-invitation.dto.ts
  src/modules/manager/manager.controller.spec.ts
  src/modules/manager/manager.controller.ts
  src/modules/manager/manager.module.ts
  src/modules/manager/manager.service.spec.ts
  src/modules/manager/manager.service.ts
  swagger.json
Labels: documentation, enhancement

#63 [FEAT] SMS 인증
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/coolsms.service.ts
  src/auth/dto/refresh-token.dto.ts
  swagger.json
Labels: documentation, enhancement

#72 feat: 자신의 관리자 및 피관리자 조회
  src/modules/manager/manager.controller.ts
  src/modules/manager/manager.module.ts
  src/modules/manager/manager.service.ts
  src/modules/users/dto/user-response.dto.ts
  swagger.json
Labels: enhancement

#74 [DOCS] swagger 업데이트
  swagger.json
Labels: documentation

#76 docs: 스웨거 업데이트
  swagger.json
Labels: documentation

#79 [FEAT] User, Auth 시더
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dto/basic-login.dto.ts
  src/auth/dto/basic-signup.dto.ts
  src/auth/dto/response.dto.ts
  src/auth/dto/verify-code.dto.ts
  src/auth/schema/response.schema.ts
  src/auth/strategies/kakao.strategy.ts
  src/auth/strategies/naver.strategy.ts
  src/dataSource.ts
  src/database/seeds/schedule.seed.ts
  src/database/seeds/user.seed.ts
  src/entities/auth.entity.ts
  src/entities/user.entity.ts
  src/main.ts
  src/modules/users/schema/response.schema.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
  swagger.json
  tsconfig.json
Labels: enhancement

#81 Refactor/manager refactoring
  src/entities/manager-invitation.entity.ts
  src/entities/schedule.entity.ts
  src/main.ts
  src/modules/manager/dto/create-invitation.dto.ts
  src/modules/manager/dto/response-invitation.dto.ts
  src/modules/manager/manager.controller.ts
  src/modules/manager/manager.module.ts
  src/modules/manager/manager.service.ts
  src/modules/schedules/schedules.service.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
  swagger.json
Labels: documentation, enhancement

#84 feat : OCR 관련 구글 클라우드 비전에서 CLOVA로 수정
  src/modules/schedules/OCR-transcription.service.ts
  src/modules/schedules/schedules.controller.ts
  src/modules/schedules/schedules.service.ts
  swagger.json
Labels: documentation, enhancement

#85 [FEAT] 그룹관련 엔티티 작성
  src/entities/group-invitation.entity.ts
  src/entities/group-schedule.entity.ts
  src/entities/group.entity.ts
  src/entities/manager-invitation.entity.ts
  src/entities/schedule.entity.ts
  src/entities/user-group.entity.ts
  src/modules/schedules/dto/response-schedule.dto.ts
  swagger.json
Labels: enhancement

#89 [FEAT] 특정 날짜의 일정 조회 API 추가 및 스케쥴 엔티티 변경, 스케쥴 userId 대신 userUuid
  src/dataSource.ts
  src/database/seeds/schedule.seed.ts
  src/database/seeds/user.seed.ts
  src/entities/schedule.entity.ts
  src/entities/user.entity.ts
  src/modules/group/group.controller.ts
  src/modules/group/group.module.ts
  src/modules/group/group.service.ts
  src/modules/schedules/dto/create-schedule.dto.ts
  src/modules/schedules/dto/data-range-schedule.dto.ts
  src/modules/schedules/dto/month-query-schedule.dto.ts
  src/modules/schedules/dto/response-schedule.dto.ts
  src/modules/schedules/dto/week-query-schedule.dto.ts
  src/modules/schedules/schedules.controller.ts
  src/modules/schedules/schedules.module.ts
  src/modules/schedules/schedules.service.ts
  swagger.json
Labels: documentation, enhancement

#91 [FEAT] 그룹 관련 API 구현
  src/modules/group/dto/create-group.dto.ts
  src/modules/group/dto/invite-group-memeber.dto.ts
  src/modules/group/dto/remove-group-member.dto.ts
  src/modules/group/dto/remove-group.dto.ts
  src/modules/group/dto/response-invitation.dto.ts
  src/modules/group/group.controller.ts
  src/modules/group/group.service.ts
  swagger.json
Labels: documentation, enhancement

#93 [FIX] 스케줄 조회 시 범위조정
  src/modules/schedules/schedules.service.ts
Labels: bug, documentation, enhancement

#95 [FEAT] user routine table 생성
  src/entities/group-invitation.entity.ts
  src/entities/group.entity.ts
  src/entities/manager-subordinate.entity.ts
  src/entities/user-group.entity.ts
  src/entities/user-routine.entity.ts
  src/entities/user.entity.ts
  swagger.json
Labels: enhancement

#98 [FEAT] user routine 관련 dto 및 api 생성
  package-lock.json
  package.json
  src/dataSource.ts
  src/entities/user-group.entity.ts
  src/entities/user-routine.entity.ts
  src/modules/group/group.service.ts
  src/modules/users/dto/response-user-routine.dto.ts
  src/modules/users/dto/update-user-routine.dto.ts
  src/modules/users/users-routine.controller.ts
  src/modules/users/users-routine.service.ts
  src/modules/users/users.module.ts
  swagger.json
Labels: documentation, enhancement

#100 [REFACTOR] 다중 그룹 멤버 추가
  src/modules/group/dto/invite-group-memeber.dto.ts
  src/modules/group/dto/response-invitation.dto.ts
  src/modules/group/group.controller.ts
  src/modules/group/group.module.ts
  src/modules/group/group.service.ts
  src/modules/users/users.module.ts
  swagger.json
Labels: documentation, enhancement

#103 Feat/user invitations
  src/app.module.ts
  src/entities/group-invitation.entity.ts
  src/entities/user.entity.ts
  src/modules/invitations/dto/invitations.dto.ts
  src/modules/invitations/invitations.controller.ts
  src/modules/invitations/invitations.module.ts
  src/modules/invitations/invitations.service.ts
  swagger.json
Labels: documentation, enhancement

#105 [FEAT] 그룹 상세 조회
  src/modules/group/dto/response-group-detail.dto.ts
  src/modules/group/dto/response-group-member.dto.ts
  src/modules/group/group.controller.ts
  src/modules/group/group.service.ts
  src/modules/users/users.service.ts
  swagger.json
Labels: documentation, enhancement

#107 [REFACTOR] 초대 조회 수정
  src/modules/invitations/dto/invitations.dto.ts
  src/modules/invitations/invitations.service.ts
  swagger.json
Labels: documentation, enhancement

#109 [FEAT] 그룹 초대 조회
  src/modules/group/dto/response-group-invitation-detail.dto.ts
  src/modules/group/group.controller.ts
  src/modules/group/group.service.ts
  swagger.json
Labels: documentation, enhancement

#111 [REFACTOR] manager response 시 이름 추가
  src/modules/manager/dto/response-invitation.dto.ts
  src/modules/manager/manager.service.ts
  swagger.json
Labels: documentation, enhancement

#112 [FEAT] 반복 일정 구현, 일정 조회 버그 수정, 일반 로그인 인증 버그 수정
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/dataSource.ts
  src/database/seeds/schedule.seed.ts
  src/entities/schedule-instance.entity.ts
  src/entities/schedule.entity.ts
  src/main.ts
  src/modules/schedules/dto/create-schedule.dto.ts
  src/modules/schedules/dto/month-query-schedule.dto.ts
  src/modules/schedules/dto/response-schedule.dto.ts
  src/modules/schedules/dto/update-schedule.dto.ts
  src/modules/schedules/dto/week-query-schedule.dto.ts
  src/modules/schedules/schedules.controller.ts
  src/modules/schedules/schedules.module.ts
  src/modules/schedules/schedules.service.ts
  src/modules/users/dto/update-user.dto.ts
  src/modules/users/users.controller.ts
  swagger.json
Labels: bug, documentation, duplicate

#114 [REFACTOR] OCR response에 반복일정 기능 삽입
  src/modules/schedules/OCR-transcription.service.ts
  src/modules/schedules/schedules.controller.ts
  src/modules/schedules/schedules.module.ts
  src/modules/schedules/schedules.service.ts
  src/modules/users/users.module.ts
  swagger.json
Labels: documentation, enhancement

#117 [REFACTOR] 관리자-피관리자 권한을 통한 일정 조회
  src/modules/manager/manager.service.ts
  src/modules/schedules/schedules.controller.ts
  src/modules/schedules/schedules.module.ts
  src/modules/schedules/schedules.service.ts
  swagger.json
Labels: documentation, enhancement

#120 [FIX] 일반 회원가입 잘못된 방식의 데이터 삽입 수정
  .github/workflows/nodejs-ci.yml
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dto/basic-signup.dto.ts
  src/entities/user.entity.ts
  swagger.json
Labels: bug

#123 [FIX] isReccuring 유효성 검사 수정
  src/modules/schedules/schedules.service.ts
Labels: bug

#125 [FIX] 일정 수정
  src/auth/dto/basic-login.dto.ts
  src/auth/dto/verify-code.dto.ts
  src/database/seeds/user.seed.ts
  src/modules/schedules/dto/update-schedule.dto.ts
  src/modules/schedules/schedules.service.ts
  swagger.json
Labels: bug

#126 [REFACTOR] 그룹 스케줄 수정
  src/modules/group/group.service.ts
  src/modules/schedules/dto/response-schedule.dto.ts
  src/modules/schedules/dto/update-schedule.dto.ts
  src/modules/schedules/schedules.service.ts
  swagger.json
Labels: documentation, enhancement
